apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: my-app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        imagePullPolicy: IfNotPresent
        image: {{ .Values.global.ImageName }}:{{ .Values.global.ImageVersion }}
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 400m
            memory: 400Mi
          requests:
            cpu: 200m     
            memory: 200Mi     
        envFrom:
        - secretRef:
            name: myapp-secrets
        volumeMounts:
        - name: app-volume
          mountPath: /project/.env
          subPath: .env
      volumes: 
      - name: app-volume
        secret:
          secretName: myapp-secrets
          items:
            - key: .env
              path: .env
