apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: myapp-secrets
  namespace: my-app
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: myapp-secrets
  files:
  - .env