apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        imagePullPolicy: Always
        image: jpvcp123/python-app:3.0
        resources:
          limits:
            cpu: 400m
            memory: 400Mi
          requests:
            cpu: 200m     
            memory: 200Mi     
        env:
          - name: POSTGRES_HOST
            value: my-postgresql.default.svc.cluster.local
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5000