name: Build & push app image

on:
  push:
    branches:
    - 'main'
    paths:
    - 'project/**'
    - '.dockerignore'
    - 'Dockerfile'

jobs:

  CI:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        id: branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          format: "DD-MM-YYYY-HH-mm"
          timeZone: 'UTC+3'

      - name: Build image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{steps.time.outputs.time}} -f Dockerfile .

      - name: Push image docker Registry
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{steps.time.outputs.time}}

      - name: update helm chart values
        uses: fjogeleit/yaml-update-action@main
        with:
          branch: ${{ steps.branch.outputs.branch }}
          targetBranch: ${{ steps.branch.outputs.branch }}
          valueFile: 'kubernetes/app-stack/values.yaml'
          commitChange: true
          message: ":recycle: refactor: Change helm chart values ${{steps.time.outputs.time}}"
          changes: |
            {
              "global.ImageName": "${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}",
              "global.ImageVersion": "${{steps.time.outputs.time}}"
            }
